name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git fetch origin
          git checkout -b output-3d origin/output-3d || git checkout -b output-3d
          git config --global user.name "${{ github.repository_owner }}[bot]"
          git config --global user.email "45850400+${{ github.repository_owner }}@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m 'temp commit' 
          git push origin output-3d --force
